# Generated by Django 6.0.2 on 2026-02-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_privatechatroom_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_audio/'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_audio/'),
        ),
    ]
